### ISSUE TITLE
 [Data 전처리] 크롤링_ ERD기준에 맞게 테이블 컬럼 변경하고, 출시일 컬럼 삭제, null로 입력된 데이터 추가

### ISSUE THREAD

**Issue by hoinnovation** [KartTrack-lap/Kartrider-game-analysis#29]
#  Issue :  [Data 전처리] 크롤링

# Description
api 데이터로 추출한 kpi데이터와 크롤링 데이터를 조인하기 위해 크롤링 데이터 전처리를 진행합니다.

# To-do
- [x] 1. ERD기준에 맞게 테이블 컬럼을 변경하는 작업을 진행합니다.
- [x] 2. 출시일과 첫 등장일 컬럼 내용이 동일해서 출시일 컬럼을 삭제합니다.
- [x] 3.  null로 입력된 데이터를 직접 추가합니다.

**Comment by hoinnovation** [comment]
# To-do 
- [x]  1. ERD기준에 맞게 테이블 컬럼을 변경하는 작업을 진행합니다.
- [x]  2. 출시일과 첫 등장일 컬럼 내용이 동일해서 출시일 컬럼을 삭제합니다.
- [x]  3. null로 입력된 데이터를 직접 추가합니다.

# Completed
#29에 모두 완료하여 이슈닫습니다!
