### ISSUE TITLE
[데이터 환경 구축] 분석 환경_컬럼명, 테이블명 수정

### ISSUE THREAD

**Issue by hyeming-king** [KartTrack-lap/Kartrider-game-analysis#35]
#  Issue : [데이터 환경 구축]

# Description
분석에 필요한 테이블에서 trigger 테이블명 변경, track_straight에서 속성 추가로 넣어주어야함
테이블 import 하면 index 함꼐 로드 됨.

# To-do

- [x] 테이블명 오타 수정 tigger -> trigger

- [x] track_straight 테이블에 straight_all_section 추가로 넣어주기

- [x] 테이블 index = False 지정하여 내보내기

**Comment by hyeming-king** [comment]
해당 내용 수정하여 업로드 완료함! 이슈 닫음
